version: "3.9"

services:
    server:
        container_name: prakticum-server
        image: prackicum-server
        env_file:
          - .env
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          - SERVER_PORT=${SERVER_PORT}
        depends_on:
          - postgres
        networks:
          - main
    postgres:
        image: postgres:14
        restart: unless-stopped
        env_file:
          - .env
        ports:
          - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_DB=${POSTGRES_DB}
        volumes:
          - postgresdata:/var/lib/postgresql/data
        networks:
          - main
    pgadmin:
        image: dpage/pgadmin4:4.18
        env_file:
          - .env
        restart: always
        environment:
          - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
          - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
          - PGADMIN_LISTEN_PORT=80
        ports:
          - "8080:80"
        volumes:
          - pgadmin:/var/lib/pgadmin
        depends_on:
          - postgres
        networks:
          - main

volumes:
    postgresdata:
        external: false
    pgadmin:
        external: false

networks:
    main:
      driver: bridge
