ARG NODE_VERSION=16
ARG SERVER_PORT=3000

FROM node:$NODE_VERSION-buster as base

RUN mkdir -p /app
WORKDIR /app

FROM base as builder

COPY . .

RUN yarn install --frozen-lockfile
RUN yarn lerna bootstrap
RUN yarn build --scope=client


FROM nginx:latest as production
WORKDIR /app

COPY --from=builder /app/packages/client/dist/ /app/

EXPOSE $SERVER_PORT
CMD [ "node", "/app/index.js" ]